theme: jekyll-theme-cayman
title: "Bill and Heathers 60th Anniversary Video"
show_downloads: False
description: "26th April 1961 to 2021"
github:
  zip_url: http://example.com/download.zip
  another_url: another value
